# Sample _config.yml file
title: My GitHub Pages Site
description: A description of my project
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
